export const customdesigns = [
  { name: "Custom Annivesary", img: "cd1.png" },
  { name: "Custom Wedding", img: "cd2.png" },
  { name: "Custom Birthday", img: "cd3.png" },
  { name: "Custom Birthday", img: "cd4.png" },
  { name: "Custom Baby Shower", img: "cd5.png" },
  { name: "Custom Graduation", img: "cd6.png" },
  { name: "Lauch Invitation", img: "cd7.png" },
  { name: "Fashion Store Design", img: "cd8.png" },
  { name: "Ramadan Seminar", img: "cd9.png" },
  { name: "Kiddies Book Design", img: "cd10.png" },
  { name: "Custom Christmas Design", img: "cd11.png" },
  { name: "", img: "cd12.png" },
  { name: "", img: "cd13.png" },
  { name: "", img: "cd14.png" },
  { name: "", img: "cd15.png" },
  { name: "", img: "cd16.png" },
  { name: "", img: "cd17.png" },
  { name: "", img: "cd18.png" },
  { name: "", img: "cd19.png" },
];

export const designPurpose = [
  "Birthday Ceremony",
  "Graduation Ceremony",
  "Wedding Ceremony",
  "Induction Ceremony",
  "Matriculation Ceremony",
  "Commercial Merchandise",
  "Naming Ceremony",
  "Branding and logo",
  "Personal Item",
  "Burial Ceremony",
  "Seminar/Career Events",
  "Pagentry",
  "Fashion Show",
  "Gala & Award Ceremony",
  "Dedication Ceremony",
  "Baby Shower",
  "Business Promotion",
  "Festival/Carnival",
  "Education Events",
  "Entertainment Events",
  "Retreat",
  "Political Events",
  "Book Cover & Magazines",
  "Exhibtion",
  "Workshop",
  "Agricultural events",
  "Conference & Expo",
  "Tourism",
  "Game/Sports",
  "Fair",
  "Others",
];
export const designTheme = [
  "Fun",
  "Minimal",
  "Typographic",
  "Masculine",
  "Kiddies",
  "Conceptual",
  "Abstract",
  "Feminine",
  "Nature",
];
export const items = [
  "Flier",
  "Sweat shirt",
  "Hoodie",
  "Cap",
  "Tshirt",
  "Flask",
  "Umbrella",
  "Water bottle",
  "Socks",
  "Pen",
  "Books",
  "Keyholder",
  "Bag",
  "Sticker",
  "Short pant",
  "Phone case",
  "Pillow",
  "Picture frame",
  "Banner",
  "Card",
  "Equipment",
  "Others",
];
