export const stats = [
  {
    title: "Completed order",
    value: "300",
    color: "#7B8A2F",
    icon: "envelop.svg",
    bgcolor: "rgba(123, 138, 47, 0.08)",
  },
  {
    title: "Overall Earning",
    value: "500k",
    color: "#3E2F8A",
    icon: "earn.svg",
    bgcolor: "#EDEDF1",
  },
  {
    title: "Overall ratings",
    value: "4.9",
    color: "#0050BA",
    icon: "star.svg",
    bgcolor: "rgba(0, 80, 186, 0.08)",
  },
  {
    title: "Job success",
    value: "99%",
    color: "#2F8A6C",
    icon: "green-check.svg",
    bgcolor: "rgba(47, 138, 108, 0.08);",
  },
  {
    title: "Cancelled order",
    value: "0",
    color: "#8A2F4D",
    icon: "green-cancel.svg",
    bgcolor: "rgba(138, 47, 77, 0.08)",
  },
];
export const designerProducts = [
  {
    image: "/assets/designer/design1.png",
    description: "We meeuve slang ...",
    author: "Shemxy",
    price: 5800,
    title: "we-move",
    usecase: 1,
  },
  {
    image: "/assets/designer/design2.png",
    description: "We meeuve slang ...",
    author: "Shemxy",
    price: 5800,
    title: "we-move",
    usecase: 1,
  },
  {
    image: "/assets/designer/design3.png",
    description: "We meeuve slang ...",
    author: "Shemxy",
    price: 5800,
    title: "we-move",
    usecase: 1,
  },
  {
    image: "/assets/designer/design4.png",
    description: "We meeuve slang ...",
    author: "Shemxy",
    price: 5800,
    title: "we-move",
    usecase: 1,
  },
  {
    image: "/assets/designer/design5.png",
    description: "We meeuve slang ...",
    author: "Shemxy",
    price: 5800,
    title: "we-move",
    usecase: 1,
  },
  {
    image: "/assets/designer/design1.png",
    description: "We meeuve slang ...",
    author: "Shemxy",
    price: 5800,
    title: "we-move",
    usecase: 1,
  },
  {
    image: "/assets/designer/design2.png",
    description: "We meeuve slang ...",
    author: "Shemxy",
    price: 5800,
    title: "we-move",
    usecase: 1,
  },
  {
    image: "/assets/designer/design3.png",
    description: "We meeuve slang ...",
    author: "Shemxy",
    price: 5800,
    title: "we-move",
    usecase: 1,
  },
  {
    image: "/assets/designer/design4.png",
    description: "We meeuve slang ...",
    author: "Shemxy",
    price: 5800,
    title: "we-move",
    usecase: 1,
  },
  {
    image: "/assets/designer/design5.png",
    description: "We meeuve slang ...",
    author: "Shemxy",
    price: 5800,
    title: "we-move",
    usecase: 1,
  },
  {
    image: "/assets/designer/design4.png",
    description: "We meeuve slang ...",
    author: "Shemxy",
    price: 5800,
    title: "we-move",
    usecase: 1,
  },
  {
    image: "/assets/designer/design5.png",
    description: "We meeuve slang ...",
    author: "Shemxy",
    price: 5800,
    title: "we-move",
    usecase: 1,
  },
];
