export const myOrders = [
  {
    updated: "13-12-22",
    designer: "Falcon Prints",
    orderTitle: "Design customisation",
    due: "2-09-2022",
    payment: "Payment Verified",
    amount: "10000",
    status: "active",
  },
  {
    updated: "13-12-22",
    designer: "Shemxy Arts",
    orderTitle: "Design customisation",
    due: "2-05-2022",
    payment: "Payment Verified",
    amount: "9000",
    status: "active",
  },
  {
    updated: "13-12-22",
    designer: "Design customisation",
    orderTitle: "Design customisation",
    due: "2-05-2022",
    payment: "Payment Verified",
    amount: "9000",
    status: "cancelled",
  },
  {
    updated: "13-12-22",
    designer: "Loju Designs",
    orderTitle: "Design customisation",
    due: "2-05-2022",
    payment: "Payment Verified",
    amount: "9000",
    status: "completed",
  },
  {
    updated: "13-12-22",
    designer: "Beam of Rays",
    orderTitle: "Design customisation",
    due: "2-05-2022",
    payment: "Payment Verified",
    amount: "9000",
    status: "completed",
  },
  {
    updated: "13-12-22",
    designer: "Faidy  Prints",
    orderTitle: "Design customisation",
    due: "2-05-2022",
    payment: "Payment Verified",
    amount: "9000",
    status: "completed",
  },
  {
    updated: "13-12-22",
    designer: "Faidy  Prints",
    orderTitle: "Design customisation",
    due: "2-05-2022",
    payment: "Payment Verified",
    amount: "9000",
    status: "completed",
  },
  {
    updated: "13-12-22",
    designer: "Falcon Prints",
    orderTitle: "Design customisation",
    due: "2-05-2022",
    payment: "Payment Verified",
    amount: "9000",
    status: "completed",
  },
  {
    updated: "13-12-22",
    designer: "Fray Design",
    orderTitle: "Design customisation",
    due: "2-05-2022",
    payment: "Payment Verified",
    amount: "9000",
    status: "completed",
  },
  {
    updated: "13-12-22",
    designer: "Fray Designn",
    orderTitle: "Design customisation",
    due: "2-05-2022",
    payment: "Payment Verified",
    amount: "9000",
    status: "completed",
  },
  {
    updated: "13-12-22",
    designer: "Fray Design",
    orderTitle: "Design customisation",
    due: "2-05-2022",
    payment: "Payment Verified",
    amount: "9000",
    status: "completed",
  },
  {
    updated: "13-12-22",
    designer: "Fray Design",
    orderTitle: "Design customisation",
    due: "2-05-2022",
    payment: "Payment Verified",
    amount: "9000",
    status: "completed",
  },
  {
    updated: "13-12-22",
    designer: "Shemzy",
    orderTitle: "Design customisation",
    due: "2-05-2022",
    payment: "Payment Verified",
    amount: "9000",
    status: "completed",
  },
];

export const printerOrders = [
  {
    updated: "13-12-22",
    designer: "Falcon Prints",
    orderTitle: "Design customisation",
    due: "2-09-2022",
    payment: "Payment Verified",
    amount: "10000",
    status: "active",
  },
  {
    updated: "13-12-22",
    designer: "Shemxy Arts",
    orderTitle: "Design customisation",
    due: "2-05-2022",
    payment: "Payment Verified",
    amount: "9000",
    status: "active",
  },

  {
    updated: "13-12-22",
    designer: "Fray Designn",
    orderTitle: "Design customisation",
    due: "2-05-2022",
    payment: "Payment Verified",
    amount: "9000",
    status: "completed",
  },
  {
    updated: "13-12-22",
    designer: "Fray Design",
    orderTitle: "Design customisation",
    due: "2-05-2022",
    payment: "Payment Verified",
    amount: "9000",
    status: "completed",
  },
  {
    updated: "13-12-22",
    designer: "Fray Design",
    orderTitle: "Design customisation",
    due: "2-05-2022",
    payment: "Payment Verified",
    amount: "9000",
    status: "completed",
  },
  {
    updated: "13-12-22",
    designer: "Fray Designn",
    orderTitle: "Design customisation",
    due: "2-05-2022",
    payment: "Payment Verified",
    amount: "9000",
    status: "cancelled",
  },
];
